"""initial_schema

Revision ID: 7e94955fd2e6
Revises: 
Create Date: 2026-04-01 03:15:44.376220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e94955fd2e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('dom_hash', sa.String(length=64), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('script_version', sa.Integer(), nullable=False),
    sa.Column('script_content', sa.Text(), nullable=True),
    sa.Column('site_fingerprint_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_records_domain_hash'), 'site_records', ['domain_hash'], unique=True)
    op.create_table('scrape_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_trace', sa.Text(), nullable=True),
    sa.Column('healing_tier_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('healing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('old_selector', sa.Text(), nullable=True),
    sa.Column('new_selector', sa.Text(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['scrape_events.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['scrape_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_results')
    op.drop_table('healing_history')
    op.drop_table('scrape_events')
    op.drop_index(op.f('ix_site_records_domain_hash'), table_name='site_records')
    op.drop_table('site_records')
    # ### end Alembic commands ###
