"""
Discovery Agent — Phase 1: human-assisted Playwright Codegen flow.

Usage:
    python -m app.discovery --url https://example.com/product --domain-hash <hash>

What it does:
  1. Launches `playwright codegen <url>` so the operator can record interactions.
  2. Prompts the operator to paste the generated script.
  3. Wraps the script in the expected run() interface.
  4. Saves it to scripts/<domain_hash>.py and updates the DB record.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import textwrap
from pathlib import Path

# Minimal bootstrap so this module can be run directly without the full app
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


SCRIPT_WRAPPER = textwrap.dedent("""\
    # Auto-generated by Discovery Agent — DO NOT EDIT the run() signature.
    # Modify the body to match site structure if needed.
    from playwright.sync_api import sync_playwright


    def run() -> dict:
        \"\"\"Execute the scrape and return a flat dict of extracted fields.\"\"\"
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            # --- BEGIN RECORDED SCRIPT ---
    {indented_body}
            # --- END RECORDED SCRIPT ---
            browser.close()
        # Replace the return value with real extracted data from the page.
        return {{
            "product_name": "",
            "price": "",
            "url": page.url,
        }}
""")

_INDENT = "        "  # 8 spaces — inside the with block


def _wrap_body(raw_body: str) -> str:
    indented = "\n".join(
        _INDENT + line if line.strip() else ""
        for line in raw_body.splitlines()
    )
    return SCRIPT_WRAPPER.format(indented_body=indented)


def run_codegen(url: str) -> None:
    print(f"\n[discovery] Launching Playwright Codegen for: {url}")
    print("[discovery] Record your interactions in the browser window, then close it.\n")
    try:
        subprocess.run(["playwright", "codegen", url], check=True)
    except FileNotFoundError:
        print("[discovery] ERROR: playwright not found. Run: pip install playwright && playwright install chromium")
        sys.exit(1)


def collect_script_from_operator() -> str:
    print("\n[discovery] Paste the generated Playwright script below.")
    print("[discovery] When finished, enter a line with only 'END' and press Enter.\n")
    lines: list[str] = []
    while True:
        try:
            line = input()
        except EOFError:
            break
        if line.strip() == "END":
            break
        lines.append(line)
    return "\n".join(lines)


def save_script(script_content: str, domain_hash: str, scripts_dir: Path) -> Path:
    scripts_dir.mkdir(parents=True, exist_ok=True)
    dest = scripts_dir / f"{domain_hash}.py"
    dest.write_text(script_content, encoding="utf-8")
    print(f"\n[discovery] Script saved to: {dest}")
    return dest


def update_db(url: str, domain_hash: str, script_content: str) -> None:
    try:
        from app.database import SessionLocal
        from app import memory

        db = SessionLocal()
        try:
            site = memory.get_site_record(db, domain_hash)
            if site is None:
                site = memory.create_site_record(db, url, domain_hash)
            memory.update_site_script(db, site, script_content)
            print(f"[discovery] DB updated — site_id={site.id} script_version={site.script_version}")
        finally:
            db.close()
    except Exception as exc:
        print(f"[discovery] WARNING: Could not update DB ({exc}). Script file is still saved.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Discovery Agent — Playwright Codegen wrapper")
    parser.add_argument("--url", required=True, help="Competitor URL to scrape")
    parser.add_argument("--domain-hash", required=True, help="Domain hash (from orchestrator output)")
    parser.add_argument(
        "--scripts-dir",
        default="scripts",
        help="Directory to store generated scripts (default: scripts/)",
    )
    parser.add_argument(
        "--skip-codegen",
        action="store_true",
        help="Skip launching browser (paste script directly)",
    )
    args = parser.parse_args()

    scripts_dir = Path(args.scripts_dir)

    if not args.skip_codegen:
        run_codegen(args.url)

    raw_body = collect_script_from_operator()
    if not raw_body.strip():
        print("[discovery] No script provided. Exiting.")
        sys.exit(1)

    wrapped = _wrap_body(raw_body)
    save_script(wrapped, args.domain_hash, scripts_dir)
    update_db(args.url, args.domain_hash, wrapped)

    print("\n[discovery] Done. You can now submit a scrape job for this URL.")


if __name__ == "__main__":
    main()
